export const events = [{
        "Department": "Computer",
        "Event Name": "C Atechism",
        "Event Code": "COMP-CQUIZ",
        "Event Price": "50",
        "Minimum Participants": "1",
        "Maximum Participants": "1",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Computer",
        "Event Name": "E-TrasureHunt",
        "Event Code": "COMP-ETRAS",
        "Event Price": "50",
        "Minimum Participants": "1",
        "Maximum Participants": "1",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Computer",
        "Event Name": "DB Mania",
        "Event Code": "COMP-DBMA",
        "Event Price": "50",
        "Minimum Participants": "1",
        "Maximum Participants": "1",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Computer",
        "Event Name": "Relay Coding",
        "Event Code": "COMP-RELAY",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Computer",
        "Event Name": "Counter Strike Game",
        "Event Code": "COMP-CSGAME",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Computer",
        "Event Name": "Need For Speed Game",
        "Event Code": "COMP-NSGAME",
        "Event Price": "50",
        "Minimum Participants": "1",
        "Maximum Participants": "1",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Applied Science",
        "Event Name": "Blind Game",
        "Event Code": "APPLIED-BLIND",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Applied Science",
        "Event Name": "The Escape Room",
        "Event Code": "APPLIED-ESCAP",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Applied Science",
        "Event Name": "Strategic Mind",
        "Event Code": "APPLIED-STRATE",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Applied Science",
        "Event Name": "Box Cricket",
        "Event Code": "APPLIED-CRIC",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Applied Science",
        "Event Name": "Memespur",
        "Event Code": "APPLIED-MEME",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Electrical",
        "Event Name": "Laserium",
        "Event Code": "ELEC-ROH",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Electrical",
        "Event Name": "Line Follower",
        "Event Code": "ELEC-LINEF",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Electrical",
        "Event Name": "Circuit Samiksha",
        "Event Code": "ELEC-CIRCUIT",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Electrical",
        "Event Name": "Maze Hunters",
        "Event Code": "ELEC-MAZE",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Civil",
        "Event Name": "Planovanie",
        "Event Code": "CIVIL-PLAN",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Civil",
        "Event Name": "Vanquish",
        "Event Code": "CIVIL-VANQ",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Civil",
        "Event Name": "Skyward Receptacle",
        "Event Code": "CIVIL-SKY",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Civil",
        "Event Name": "Cyto Spark",
        "Event Code": "CIVIL-CYTO",
        "Event Price": "50",
        "Minimum Participants": "3",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Mechanical",
        "Event Name": "Junkyard",
        "Event Code": "MECH-ARENA",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Mechanical",
        "Event Name": "Smash On",
        "Event Code": "MECH-SMASH",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Mechanical",
        "Event Name": "CAD Snapper",
        "Event Code": "MECH-CAD",
        "Event Price": "50",
        "Minimum Participants": "1",
        "Maximum Participants": "1",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "Mechanical",
        "Event Name": "Interbrains Debate Competition",
        "Event Code": "MECH-DEBATE",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "E&C",
        "Event Name": "Death Race",
        "Event Code": "EC-DEATH",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "E&C",
        "Event Name": "Bomb Diffuser",
        "Event Code": "EC-BOMB",
        "Event Price": "50",
        "Minimum Participants": "2",
        "Maximum Participants": "2",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "E&C",
        "Event Name": "Big Capitalist",
        "Event Code": "EC-CAPT",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    },
    {
        "Department": "E&C",
        "Event Name": "Bowling Mania",
        "Event Code": "EC-BOWLING",
        "Event Price": "50",
        "Minimum Participants": "4",
        "Maximum Participants": "4",
        "Description": "",
        "Rules": "",
        "images": "/images/events/"
    }
];